
set(MATHEX_SOURCES
    AlignedBox2d.cpp
    AlignedBox2d.hpp
    AlignedBox3d.cpp
    AlignedBox3d.hpp
    Angle.cpp
    Angle.hpp
    CompressedAlignedBox2d.cpp
    CompressedAlignedBox2d.hpp
    Circle2d.cpp
    Circle2d.hpp
    CompressedLine3d.cpp
    CompressedLine3d.hpp
    CoordSystem.cpp
    CoordSystem.hpp
    CompressedPoint2d.cpp
    CompressedPoint2d.hpp
    CompressedPoint3d.cpp
    CompressedPoint3d.hpp
    CompressedTransform3d.cpp
    CompressedTransform3d.hpp
    CompressedVec3.cpp
    CompressedVec3.hpp
    ConvexPolygon2d.cpp
    ConvexPolygon2d.hpp
    Degrees.cpp
    Degrees.hpp
    Double.cpp
    Double.hpp
    Epsilon.cpp
    Epsilon.hpp
    EulerAngles.cpp
    EulerAngles.hpp
    Grid2d.cpp
    Grid2d.hpp
    HalfPlane2d.cpp
    HalfPlane2d.hpp
    HalfSpace3d.cpp
    HalfSpace3d.hpp
    Intersections.cpp
    Intersections.hpp
    Line2d.cpp
    Line2d.hpp
    Line3d.cpp
    Line3d.hpp
    mathex.cpp
    mathex.hpp
    Outcode.cpp
    Outcode.hpp
    Plane3d.cpp
    Plane3d.hpp
    Point2d.cpp
    Point2d.hpp
    Point3d.cpp
    Point3d.hpp
    Polygon2d.cpp
    Polygon2d.hpp
    Quad3d.cpp
    Quad3d.hpp
    Quadratic.cpp
    Quadratic.hpp
    Quaternion.cpp
    Quaternion.hpp
    Radians.cpp
    Radians.hpp
    Random.cpp
    Random.hpp
    Sausage2d.cpp
    Sausage2d.hpp
    Size2d.cpp
    Size2d.hpp
    Sphere3d.cpp
    Sphere3d.hpp
    Transform3dKey.cpp
    Transform3dKey.hpp
    Transform3d.cpp
    Transform3d.hpp
    Triangle2d.cpp
    Triangle2d.hpp
    Utility.cpp
    Utility.hpp
    Vec2.cpp
    Vec2.hpp
    Vec3.cpp
    Vec3.hpp
)

add_library(mathex ${GAME_COMPONENT_LIB_TYPE} ${MATHEX_SOURCES})
add_library(LibDev::mathex ALIAS mathex)

target_link_libraries(mathex PUBLIC
    LibDev::base
    LibDev::recorder
)
