
set(WORLD4D_SOURCES
    Complexity.cpp
    DebugTimer.hpp
    DXErrorHandler.hpp
    Entity/BoundingBoxSelector.cpp
    Entity/BoundingBoxSelector.hpp
    Entity/Composite.cpp
    Entity/Composite.hpp
    Entity/CompositeImpl.cpp
    Entity/CompositePlan.cpp
    Entity/CompositePlan.hpp
    Entity/CompositePlanEntry.cpp
    Entity/CompositePlanEntry.hpp
    Entity/CompositePlanImpl.cpp
    Entity/Custom.cpp
    Entity/Custom.hpp
    Entity/Custom.ipp
    Entity/Entity.cpp
    Entity/Entity.hpp
    Entity/EntityFilter.cpp
    Entity/EntityFilter.hpp
    Entity/EntityImpl.cpp
    Entity/EntityIter.cpp
    Entity/EntityIter.hpp
    Entity/EntityPlan.cpp
    Entity/EntityPlan.hpp
    Entity/EntityScale.cpp
    Entity/EntityScale.hpp
    Entity/EntityScale.ipp
    Entity/Generic.cpp
    Entity/Generic.hpp
    Entity/GenericComposite.cpp
    Entity/GenericComposite.hpp
    Entity/GenericRepository.cpp
    Entity/GenericRepository.hpp
    Entity/GenericRepository.ipp
    Entity/Internal/CompositeImpl.hpp
    Entity/Internal/CompositePlanImpl.hpp
    Entity/Internal/EntityImpl.hpp
    Entity/Internal/EntityImpl.ipp
    Entity/Internal/PlanFunctions.ctf
    Entity/Internal/PlanFunctions.hpp
    Entity/Link.cpp
    Entity/Link.hpp
    Entity/Link.ipp
    Entity/MotionControlledEntity.cpp
    Entity/MotionControlledEntity.hpp
    Entity/Root.cpp
    Entity/Root.hpp
    Entity/SpinSprite.cpp
    Entity/SpinSprite.hpp
    Entity/Sprite3d.cpp
    Entity/Sprite3d.hpp
    ForwardMaterials.hpp
    ForwardPlans.hpp
    Internal/Complexity.hpp
    Internal/w4d_pch.hpp
    Logger.cpp
    Logger.hpp
    Manager.cpp
    Manager.hpp
    Manager.ipp
    Materials/AnimationData.cpp
    Materials/CompositeMaterialVecChanger.cpp
    Materials/CompositeMaterialVecChanger.hpp
    Materials/CycleTextureData.cpp
    Materials/EntityMaterialVecChanger.cpp
    Materials/EntityMaterialVecChanger.hpp
    Materials/Internal/AnimationData.hpp
    Materials/Internal/CycleTextureData.hpp
    Materials/Internal/MultiColour.hpp
    Materials/Internal/MultiTexture.hpp
    Materials/Internal/UVData.hpp
    Materials/MaterialVecPtrCompLess.cpp
    Materials/MaterialVecPtrCompLess.hpp
    Materials/MultiColour.cpp
    Materials/MultiTexture.cpp
    Materials/UVData.cpp
    Persistence.cpp
    Persistence.hpp
    Plans/ColourPlanData.cpp
    Plans/ColourPlanData.hpp
    Plans/ColourPulseData.cpp
    Plans/ColourPulseData.hpp
    Plans/ColourPulsePlan.cpp
    Plans/ColourPulsePlan.hpp
    Plans/FloatValuePlan.cpp
    Plans/FloatValuePlan.hpp
    Plans/GeneralUniformScalePlan.cpp
    Plans/GeneralUniformScalePlan.hpp
    Plans/Internal/PendingPlan.ctf
    Plans/Internal/PendingPlan.hpp
    Plans/LinearFloatValuePlan.cpp
    Plans/LinearFloatValuePlan.hpp
    Plans/MaterialFramePlan.cpp
    Plans/MaterialFramePlan.hpp
    Plans/MaterialPlan.cpp
    Plans/MaterialPlan.hpp
    Plans/MaterialPlan.ipp
    Plans/MaterialSequencePlan.cpp
    Plans/MaterialSequencePlan.hpp
    Plans/MaterialSequencePlan.ipp
    Plans/MeshPlan.cpp
    Plans/MeshPlan.hpp
    Plans/PendingPlan.ctf
    Plans/PendingPlan.ctp
    Plans/PendingPlan.hpp
    Plans/ScalePlan.cpp
    Plans/ScalePlan.hpp
    Plans/ScalePlan.ipp
    Plans/SimpleAlphaPlan.cpp
    Plans/SimpleAlphaPlan.hpp
    Plans/SimpleEmColPlan.cpp
    Plans/SimpleEmColPlan.hpp
    Plans/SimpleIntensityPlan.cpp
    Plans/SimpleIntensityPlan.hpp
    Plans/SimpleScalePlan.cpp
    Plans/SimpleScalePlan.hpp
    Plans/SolidFadedAlphaPlan.cpp
    Plans/SolidFadedAlphaPlan.hpp
    Plans/UVPlan.cpp
    Plans/UVPlan.hpp
    Plans/UVTranslation.cpp
    Plans/UVTranslation.hpp
    Plans/VisibilityPlan.cpp
    Plans/VisibilityPlan.hpp
    Scene/Background.cpp
    Scene/Background.hpp
    Scene/Camera.cpp
    Scene/Camera.hpp
    Scene/CameraShake.cpp
    Scene/CameraShake.hpp
    Scene/CameraShake.ipp
    Scene/CameraVolume.cpp
    Scene/CameraVolume.hpp
    Scene/Domain.cpp
    Scene/Domain.hpp
    Scene/DomainAssignor.hpp
    Scene/DomainImpl.cpp
    Scene/Environment.cpp
    Scene/Environment.hpp
    Scene/GarbageCollector.cpp
    Scene/GarbageCollector.hpp
    Scene/Internal/DomainImpl.hpp
    Scene/Internal/LightData.hpp
    Scene/Internal/LightImpl.hpp
    Scene/Internal/NoLight.hpp
    Scene/Light.cpp
    Scene/Light.hpp
    Scene/LightData.cpp
    Scene/LocalLightList.cpp
    Scene/LocalLightList.hpp
    Scene/NoLight.cpp
    Scene/Portal.cpp
    Scene/Portal.hpp
    Scene/SceneManager.cpp
    Scene/SceneManager.hpp
    Scene/Shadow.cpp
    Scene/Shadow.hpp
    Scene/Stars.cpp
    Scene/Stars.hpp
    Scene/Stars.ipp
    Sound/Internal/SoundData.hpp
    Sound/Internal/SoundData.ipp
    Sound/Internal/SoundManagerImpl.hpp
    Sound/SoundData.cpp
    Sound/SoundManager.cpp
    Sound/SoundManager.hpp
    Sound/SoundManagerImpl.cpp
    Subject/Internal/SubjectImpl.hpp
    Subject/Observer.cpp
    Subject/Observer.hpp
    Subject/Observer.ipp
    Subject/ObserverForward.hpp
    Subject/Subject.cpp
    Subject/Subject.hpp
    Subject/SubjectForward.hpp
    Subject/SubjectImpl.cpp
    Tracking/AxisTrackerPlan.cpp
    Tracking/AxisTrackerPlan.hpp
    Tracking/AxisTrackerPlan.ipp
    Tracking/AxisTurnerPlan.cpp
    Tracking/AxisTurnerPlan.hpp
    Tracking/FrameRegulator.cpp
    Tracking/FrameRegulator.hpp
    Tracking/FrameRegulator.ipp
    Tracking/ObjectTracker.cpp
    Tracking/ObjectTracker.hpp
    Tracking/ObjectTracker.ipp
    Tracking/ObjectTrackerMotionPlan.cpp
    Tracking/ObjectTrackerMotionPlan.hpp
    Tracking/ObjectTrackerScalePlan.cpp
    Tracking/ObjectTrackerScalePlan.hpp
    world4d.hpp
)

add_library(world4d STATIC ${WORLD4D_SOURCES})
add_library(LibDev::world4d ALIAS world4d)

target_link_libraries(world4d PUBLIC
    LibDev::base
    LibDev::render
    LibDev::sound
)
