
set(BASE_SOURCES
    IProgressReporter.hpp
    PersistenceFlagsInBool.cpp
    PersistenceFlagsInBool.hpp
    AppendBufferStream.cpp
    AppendStream.cpp
    base.cpp
    base.hpp
    ConcurrentBlockAllocator.cpp
    ConcurrentBlockAllocator.hpp
    compiler.hpp
    ConstBufferStream.cpp
    Diag.cpp
    Diag.hpp
    DiagInternal.cpp
    DiagStream.cpp
    DiagStreams.cpp
    DiagStreamType.hpp
    Error.cpp
    Error.hpp
    FilterBufferStream.cpp
    Filter.cpp
    Indent.cpp
    IndirectFilterStream.cpp
    internal/AppendBufferStream.hpp
    internal/AppendStream.hpp
    internal/ConstBufferStream.hpp
    internal/DiagStream.hpp
    internal/DiagStreams.hpp
    internal/FilterBufferStream.hpp
    internal/IndirectFilterStream.hpp
    internal/IstreamBuffer.hpp
    internal/IstreamImpl.hpp
    internal/LogStreamBuffer.hpp
    internal/OstreamBuffer.hpp
    internal/PersistRead.hpp
    internal/PersistWrite.hpp
    internal/PersistLog.hpp
    internal/Persistence.hpp
    internal/PrependBufferStream.hpp
    internal/PrependStream.hpp
    internal/TrackerImpl.hpp
    internal/WindStr.hpp
    PerIstream.cpp
    PerIstream.hpp
    IstreamBuffer.cpp
    IstreamImpl.cpp
    LessPtr.hpp
    LogBuffer.cpp
    LogBuffer.hpp
    LogStreamBuffer.cpp
    MemChkData.cpp
    MemChkData.hpp
    MemChk.cpp
    MemChk.hpp
    MemWatcher.cpp
    MemWatcher.hpp
    PerOstream.cpp
    PerOstream.hpp
    PersistRead.cpp
    PersistWrite.cpp
    PersistLog.cpp
    Persistence.cpp
    Persistence.hpp
    PoolAllocator.cpp
    PoolAllocator.hpp
    PrependBufferStream.cpp
    PrependStream.cpp
    PrePost.cpp
    PrePost.hpp
    private/DiagInternal.hpp
    private/DualStream.hpp
    private/Filter.hpp
    private/Indent.hpp
    private/Persistence.hpp
    private/PersistTypes.hpp
    private/Trace.hpp
    private/Tracker.hpp
    Trace.cpp
    Tracker.cpp
    Tracker.hpp
    TrackerImpl.cpp
)

add_library(base ${GAME_COMPONENT_LIB_TYPE} ${BASE_SOURCES})
add_library(LibDev::base ALIAS base)

target_link_libraries(base PUBLIC
    LibDev::stdlib

    spdlog::spdlog
)
