
set(MACHGUI_SOURCES
    ActorBitmaps.cpp
    ActorBitmaps.hpp
    ActorStringIdRestorer.cpp
    ActorStringIdRestorer.hpp
    Animation.cpp
    Animation.hpp
    AutoDeleteDisplayable.cpp
    AutoDeleteDisplayable.hpp
    BindId.hpp
    BindsStorageXml.cpp
    BindsStorageXml.hpp
    BmuText.cpp
    BmuText.hpp
    BufferScrollButton.cpp
    BufferScrollButton.hpp
    BuildMachineIcon.cpp
    BuildMachineIcon.hpp
    BuildMenu.cpp
    BuildMenu.hpp
    BuildMenuIcons.cpp
    BuildMenuIcons.hpp
    BuildProgressBar.cpp
    BuildProgressBar.hpp
    CameraScrollArea.cpp
    CameraScrollArea.hpp
    Cameras.cpp
    Cameras.hpp
    ChatWindow.cpp
    ChatWindow.hpp
    CommandIcons.cpp
    CommandIcons.hpp
    ConsoleCommands.cpp
    ConsoleCommands.hpp
    ConsoleDropDown.cpp
    ConsoleDropDown.hpp
    ConstructMenu.cpp
    ConstructMenu.hpp
    ConstructMenuIcons.cpp
    ConstructMenuIcons.hpp
    ConstructionSelectIcon.cpp
    ConstructionSelectIcon.hpp
    ContinentMap.cpp
    ContinentMap.cpp
    ContinentMap.hpp
    ContinentMap.hpp
    ControlPanel.cpp
    ControlPanel.hpp
    ControlPanelAddOn.cpp
    ControlPanelAddOn.hpp
    ControlPanelImpl.cpp
    CorralSingleIconInfo.cpp
    CorralSingleIconInfo.hpp
    CursorSpec.cpp
    CursorSpec.hpp
    DispositionChangeNotifiable.cpp
    DispositionChangeNotifiable.hpp
    DropDownListBox.cpp
    DropDownListBox.hpp
    DropDownListBoxCreator.cpp
    DropDownListBoxCreator.hpp
    EditBoxListBoxItem.cpp
    EditBoxListBoxItem.hpp
    ExitToInternetMessageBoxResponder.cpp
    ExitToInternetMessageBoxResponder.hpp
    FactoryBuffer.cpp
    FactoryBuffer.hpp
    FirstPerson.cpp
    FirstPerson.hpp
    FocusCapableControl.cpp
    FocusCapableControl.hpp
    GameMenuContext.cpp
    GameMenuContext.hpp
    GeneralStatistics.cpp
    GeneralStatistics.hpp
    HWResearchBank.cpp
    HWResearchBank.hpp
    HWResearchBankIcons.cpp
    HWResearchBankIcons.hpp
    HWResearchIcon.cpp
    HWResearchIcon.hpp
    HWResearchIcons.cpp
    HWResearchIcons.hpp
    HWResearchMenu.cpp
    HWResearchMenu.hpp
    HealthBar.cpp
    HealthBar.hpp
    IBindsStorage.hpp
    IInputRegistry.hpp
    IconWithCounter.cpp
    IconWithCounter.hpp
    InGameChatMessages.cpp
    InGameChatMessages.hpp
    InGameChatMessagesDisplay.cpp
    InGameChatMessagesDisplay.hpp
    InGameScreen.cpp
    InGameScreen.hpp
    InGameScreenKeyboard.cpp
    InputLayout.cpp
    InputLayout.hpp
    InputRegistry.cpp
    InputRegistry.hpp
    IntelligentCursorOnActor.cpp
    IntelligentCursorOnActor.hpp
    KeyToString.cpp
    KeyToString.hpp
    LoadSaveGameExtras.cpp
    LoadSaveGameExtras.hpp
    MachGuiFPCommand.cpp
    MachGuiFPCommand.hpp
    MapArea.cpp
    MapArea.hpp
    MapAreaImpl.cpp
    MenuContext/CtxBriefing.cpp
    MenuContext/CtxBriefing.hpp
    MenuContext/CtxCampaign.cpp
    MenuContext/CtxCampaign.hpp
    MenuContext/CtxDeBriefing.cpp
    MenuContext/CtxDeBriefing.hpp
    MenuContext/CtxHotKeys.cpp
    MenuContext/CtxHotKeys.hpp
    MenuContext/CtxImReady.cpp
    MenuContext/CtxImReady.hpp
    MenuContext/CtxInGameOptions.cpp
    MenuContext/CtxInGameOptions.hpp
    MenuContext/CtxJoin.cpp
    MenuContext/CtxJoin.hpp
    MenuContext/CtxLoad.cpp
    MenuContext/CtxLoad.hpp
    MenuContext/CtxMainMenu.cpp
    MenuContext/CtxMainMenu.hpp
    MenuContext/CtxMultiplayer.cpp
    MenuContext/CtxMultiplayer.hpp
    MenuContext/CtxOptions.cpp
    MenuContext/CtxOptions.hpp
    MenuContext/CtxSave.cpp
    MenuContext/CtxSave.hpp
    MenuContext/CtxScenario.cpp
    MenuContext/CtxScenario.hpp
    MenuContext/CtxSettings.cpp
    MenuContext/CtxSettings.hpp
    MenuContext/CtxSinglePlayer.cpp
    MenuContext/CtxSinglePlayer.hpp
    MenuContext/CtxSkirmish.cpp
    MenuContext/CtxSkirmish.hpp
    MenuContext/CtxStatistics.cpp
    MenuContext/CtxStatistics.hpp
    MessageBoxResponder.cpp
    MessageBoxResponder.hpp
    MessageBroker.cpp
    MessageBroker.hpp
    MessageDisplay.cpp
    MessageDisplay.hpp
    MexTemp.cpp
    MexTemp.hpp
    NavigatorBase.cpp
    NavigatorBase.hpp
    Network/ConnectionType.cpp
    Network/ConnectionType.hpp
    Network/IPXNetworkMode.cpp
    Network/IPXNetworkMode.hpp
    Network/InternetNetworkMode.cpp
    Network/InternetNetworkMode.hpp
    Network/ModemNetworkMode.cpp
    Network/ModemNetworkMode.hpp
    Network/NetworkProtocolMode.cpp
    Network/NetworkProtocolMode.hpp
    Network/NetworkVariables.cpp
    Network/NetworkVariables.hpp
    Network/SerialNetworkMode.cpp
    Network/SerialNetworkMode.hpp
    NewCorralIcon.cpp
    NewCorralIcon.hpp
    NewProductionIcon.cpp
    NewProductionIcon.hpp
    NewResearchIcon.cpp
    NewResearchIcon.hpp
    NumPlayersDropDownListBoxCreator.cpp
    NumPlayersDropDownListBoxCreator.hpp
    PausedImage.cpp
    PausedImage.hpp
    PlayerColour.cpp
    PlayerColour.hpp
    PlayerNameList.cpp
    PlayerScore.cpp
    ProductionBank.cpp
    ProductionBank.hpp
    ProductionIcons.cpp
    ProductionIcons.hpp
    ProgressIndicator.cpp
    ProgressIndicator.hpp
    PromptText.cpp
    PromptText.hpp
    Radar.cpp
    Radar.hpp
    SingleLineEditBox.cpp
    SingleLineEditBox.hpp
    SingleSelectionListBox.cpp
    SingleSelectionListBox.hpp
    SingleSelectionListBoxItem.cpp
    SingleSelectionListBoxItem.hpp
    SoundManager.cpp
    SquadronBank.cpp
    SquadronBank.hpp
    StartupData.cpp
    StartupData.hpp
    StartupScreenContext.cpp
    StartupScreenContext.hpp
    StartupScreens.cpp
    StartupScreens.hpp
    Statistics.cpp
    Statistics.hpp
    StatisticsBar.cpp
    StatisticsBar.hpp
    StatisticsDisplay.cpp
    StatisticsDisplay.hpp
    SystemMessageHandler.cpp
    SystemMessageHandler.hpp
    TypeRestorer.cpp
    TypeRestorer.hpp
    VSyncMode.cpp
    VSyncMode.hpp
    WorldViewWindow.cpp
    WorldViewWindow.hpp
    commands/CommandAssemblyPoint.cpp
    commands/CommandAssemblyPoint.hpp
    commands/CommandAttack.cpp
    commands/CommandAttack.hpp
    commands/CommandBuild.cpp
    commands/CommandBuild.hpp
    commands/CommandCamouflage.cpp
    commands/CommandCamouflage.hpp
    commands/CommandCapture.cpp
    commands/CommandCapture.hpp
    commands/CommandConstruct.cpp
    commands/CommandConstruct.hpp
    commands/CommandDeconstruct.cpp
    commands/CommandDeconstruct.hpp
    commands/CommandDefault.cpp
    commands/CommandDefault.hpp
    commands/CommandDefcon.cpp
    commands/CommandDefcon.hpp
    commands/CommandDeploy.cpp
    commands/CommandDeploy.hpp
    commands/CommandDropLandMine.cpp
    commands/CommandDropLandMine.hpp
    commands/CommandFormSquadron.cpp
    commands/CommandFormSquadron.hpp
    commands/CommandHeal.cpp
    commands/CommandHeal.hpp
    commands/CommandIonAttack.cpp
    commands/CommandIonAttack.hpp
    commands/CommandLocateTo.cpp
    commands/CommandLocateTo.hpp
    commands/CommandMove.cpp
    commands/CommandMove.hpp
    commands/CommandNukeAttack.cpp
    commands/CommandNukeAttack.hpp
    commands/CommandPatrol.cpp
    commands/CommandPatrol.hpp
    commands/CommandPickUp.cpp
    commands/CommandPickUp.hpp
    commands/CommandRecycle.cpp
    commands/CommandRecycle.hpp
    commands/CommandRefillLandMine.cpp
    commands/CommandRefillLandMine.hpp
    commands/CommandRepair.cpp
    commands/CommandRepair.hpp
    commands/CommandResearch.cpp
    commands/CommandResearch.hpp
    commands/CommandScavenge.cpp
    commands/CommandScavenge.hpp
    commands/CommandSelfDestruct.cpp
    commands/CommandSelfDestruct.hpp
    commands/CommandStandGround.cpp
    commands/CommandStandGround.hpp
    commands/CommandStop.cpp
    commands/CommandStop.hpp
    commands/CommandTransport.cpp
    commands/CommandTransport.hpp
    commands/CommandTreachery.cpp
    commands/CommandTreachery.hpp
    commands/command.cpp
    commands/command.hpp
    commands/commandi.cpp
    commands/commandi.hpp
    db/Database.cpp
    db/Database.hpp
    db/DatabaseHandler.cpp
    db/DatabaseHandler.hpp
    db/DbElement.cpp
    db/DbElement.hpp
    db/DbIDatabase.cpp
    db/DbIElement.cpp
    db/DbIPlanet.cpp
    db/DbIPlayer.cpp
    db/DbIPlayerScenario.cpp
    db/DbISavedGame.cpp
    db/DbIScenario.cpp
    db/DbISystem.cpp
    db/DbITextData.cpp
    db/DbPlanet.cpp
    db/DbPlanet.hpp
    db/DbPlayer.cpp
    db/DbPlayer.hpp
    db/DbPlayerScenario.cpp
    db/DbPlayerScenario.hpp
    db/DbSavedGame.cpp
    db/DbSavedGame.hpp
    db/DbScenario.cpp
    db/DbScenario.hpp
    db/DbSystem.cpp
    db/DbSystem.hpp
    db/DbTextData.cpp
    db/DbTextData.hpp
    db/internal/DbIDatabase.hpp
    db/internal/DbIElement.hpp
    db/internal/DbIPlanet.hpp
    db/internal/DbIPlayer.hpp
    db/internal/DbIPlayerScenario.hpp
    db/internal/DbISavedGame.hpp
    db/internal/DbIScenario.hpp
    db/internal/DbISystem.hpp
    db/internal/DbITextData.hpp
    gui.cpp
    gui.hpp
    internal/ControlPanelImpl.hpp
    internal/InGameScreenImpl.hpp
    internal/MapAreaImpl.hpp
    internal/PlayerNameList.hpp
    internal/PlayerScore.hpp
    internal/SoundManager.hpp
    internal/StartupScreensImpl.hpp
    internal/strings.hpp
    menus_helper.cpp
    menus_helper.hpp
    root.hpp
    ui/CheckBox.cpp
    ui/CheckBox.hpp
    ui/MenuButton.cpp
    ui/MenuButton.hpp
    ui/MenuStyle.cpp
    ui/MenuStyle.hpp
    ui/MenuText.cpp
    ui/MenuText.hpp
    ui/ScrollArea.cpp
    ui/ScrollArea.hpp
    ui/ScrollableText.cpp
    ui/ScrollableText.hpp
    ui/SlideBar.cpp
    ui/SlideBar.hpp
    ui/Text.cpp
    ui/Text.hpp
    ui/VerticalScrollBar.cpp
    ui/VerticalScrollBar.hpp
)

add_library(machgui ${GAME_COMPONENT_LIB_TYPE} ${MACHGUI_SOURCES})
add_library(LibDev::machgui ALIAS machgui)

target_link_libraries(machgui PUBLIC
    LibDev::ani
    LibDev::gui
    LibDev::machlog
    LibDev::network
    LibDev::version
)
