
set(GXIN_SOURCES
    Color.cpp
    Color.hpp
    Data.hpp
    Error.hpp
    File.cpp
    File.hpp
    Gen.hpp
    Hierarchy.cpp
    Hierarchy.hpp
    gxin.hpp
    IdPos.cpp
    IdPos.hpp
    Label.cpp
    Label.hpp
    Material.cpp
    Material.hpp
    Matrix3.cpp
    Matrix3.hpp
    GXMesh.cpp
    GXMesh.hpp
    Name.hpp
    Point3.cpp
    Point3.hpp
    Polygon3.cpp
    Polygon3.hpp
    PolyVert3.cpp
    PolyVert3.hpp
    GXTexture.cpp
    GXTexture.hpp
    Textures.hpp
    UVCoords.cpp
    UVCoords.hpp
    Vec3.cpp
    Vec3.hpp
    Vec4.cpp
    Vec4.hpp
)

add_library(gxin OBJECT ${GXIN_SOURCES})
