
set(MACHPHYS_SOURCES
    Artefact.cpp
    Artefact.hpp
    Artefact.ipp
    ArtefactData.cpp
    ArtefactData.hpp
    ArtefactData.ipp
    CanBeDestroyed.hpp
    ComplexityItem.cpp
    ComplexityItem.hpp
    ComplexityManager.cpp
    ComplexityManager.hpp
    Constructions/Beacon.cpp
    Constructions/Beacon.hpp
    Constructions/BeaconData.cpp
    Constructions/BeaconData.hpp
    Constructions/Construction.cpp
    Constructions/Construction.hpp
    Constructions/ConstructionData.cpp
    Constructions/ConstructionData.hpp
    Constructions/ConstructionData.ipp
    Constructions/ConstructionExplosionData.cpp
    Constructions/ConstructionExplosionData.hpp
    Constructions/ConstructionImpl.cpp
    Constructions/Door.cpp
    Constructions/Door.hpp
    Constructions/Entrance.cpp
    Constructions/Entrance.hpp
    Constructions/Factory.cpp
    Constructions/Factory.hpp
    Constructions/FactoryData.cpp
    Constructions/FactoryData.hpp
    Constructions/Garrison.cpp
    Constructions/Garrison.hpp
    Constructions/GarrisonData.cpp
    Constructions/GarrisonData.hpp
    Constructions/HardwareLab.cpp
    Constructions/HardwareLab.hpp
    Constructions/HardwareLabData.cpp
    Constructions/HardwareLabData.hpp
    Constructions/Internal/ConstructionDataImpl.hpp
    Constructions/Internal/ConstructionImpl.hpp
    Constructions/Mine.cpp
    Constructions/Mine.hpp
    Constructions/MineData.cpp
    Constructions/MineData.hpp
    Constructions/MissileEmplacement.cpp
    Constructions/MissileEmplacement.hpp
    Constructions/MissileEmplacementData.cpp
    Constructions/MissileEmplacementData.hpp
    Constructions/Pod.cpp
    Constructions/Pod.hpp
    Constructions/PodData.cpp
    Constructions/PodData.hpp
    Constructions/Smelter.cpp
    Constructions/Smelter.hpp
    Constructions/SmelterData.cpp
    Constructions/SmelterData.hpp
    Constructions/SoftwareLabData.cpp
    Constructions/SoftwareLabData.hpp
    Constructions/Station.cpp
    Constructions/Station.hpp
    Constructions/Stations.cpp
    Constructions/Stations.hpp
    Constructions/WeaponsLabData.cpp
    Constructions/WeaponsLabData.hpp
    Data/Data.cpp
    Data/Data.hpp
    Data/DataImplementation.cpp
    Data/DataParser.cpp
    Data/GeneralData.cpp
    Data/GeneralData.hpp
    Data/Internal/DataImplementation.ctf
    Data/Internal/DataImplementation.hpp
    Data/Internal/DataParser.hpp
    Data/LevelIndexMap.cpp
    Data/LevelIndexMap.hpp
    Data/Levels.cpp
    Data/Levels.hpp
    Data/LinkData.cpp
    Data/LinkData.hpp
    Data/ObjectData.cpp
    Data/ObjectData.hpp
    Data/Preload.cpp
    Data/Preload.hpp
    Data/SoundData.hpp
    Data/SoundPlan.cpp
    Data/SoundPlan.hpp
    Effects/Beam.cpp
    Effects/Beam.hpp
    Effects/BeeBombExplosion.cpp
    Effects/BeeBombExplosion.hpp
    Effects/BeeBombWave.cpp
    Effects/BeeBombWave.hpp
    Effects/BlackSphere.cpp
    Effects/BlackSphere.hpp
    Effects/Blast.cpp
    Effects/Blast.hpp
    Effects/BurstWave.cpp
    Effects/BurstWave.hpp
    Effects/CrackFire.cpp
    Effects/CrackFire.hpp
    Effects/CrackFireImpl.cpp
    Effects/Debris.cpp
    Effects/Debris.hpp
    Effects/DebrisUnit.cpp
    Effects/DebrisUnit.hpp
    Effects/DoublesidedFlame.cpp
    Effects/DoublesidedFlame.hpp
    Effects/Effects.cpp
    Effects/Effects.hpp
    Effects/EntityDamage.cpp
    Effects/EntityDamage.hpp
    Effects/EntityDamageImpl.cpp
    Effects/ExplosionPoint.cpp
    Effects/Fireball.cpp
    Effects/Fireball.hpp
    Effects/FireballImpl.cpp
    Effects/Flame.cpp
    Effects/Flame.hpp
    Effects/FlameBall.cpp
    Effects/FlameBall.hpp
    Effects/FlashDisc.cpp
    Effects/FlashDisc.hpp
    Effects/GenericExplosionData.cpp
    Effects/GenericExplosionData.hpp
    Effects/GroundSplat.cpp
    Effects/GroundSplat.hpp
    Effects/HealAura.cpp
    Effects/HealAura.hpp
    Effects/HealHelix.cpp
    Effects/HealHelix.hpp
    Effects/Helix.cpp
    Effects/Helix.hpp
    Effects/HemiSphere.cpp
    Effects/HemiSphere.hpp
    Effects/IHealthMaterials.cpp
    Effects/Internal/CrackFireImpl.hpp
    Effects/Internal/EntityDamageImpl.hpp
    Effects/Internal/FireballImpl.hpp
    Effects/Internal/IHealthMaterials.hpp
    Effects/Internal/RaceChangerBody.hpp
    Effects/IonBeam.cpp
    Effects/IonBeam.hpp
    Effects/JetRing.cpp
    Effects/JetRing.hpp
    Effects/JetRingPlan.cpp
    Effects/JetRingPlan.hpp
    Effects/Light.cpp
    Effects/Light.hpp
    Effects/LightStingAura.cpp
    Effects/LightStingAura.hpp
    Effects/LightStingSplat.cpp
    Effects/LightStingSplat.hpp
    Effects/LightningHalo.cpp
    Effects/LightningHalo.hpp
    Effects/LightningHaloMaterialPlan.cpp
    Effects/LightningHaloMaterialPlan.hpp
    Effects/LoadingLight.cpp
    Effects/LoadingLight.hpp
    Effects/LoadingOver.cpp
    Effects/LoadingOver.hpp
    Effects/LoadingUnder.cpp
    Effects/LoadingUnder.hpp
    Effects/MachineBurning.cpp
    Effects/MachineBurning.hpp
    Effects/MachineDamage.cpp
    Effects/MachineDamage.hpp
    Effects/MachineExplosion.cpp
    Effects/MachineExplosion.hpp
    Effects/MushroomEdge.cpp
    Effects/MushroomEdge.hpp
    Effects/MushroomShaft.cpp
    Effects/MushroomShaft.hpp
    Effects/MushroomTop.cpp
    Effects/MushroomTop.hpp
    Effects/NuclearBomb.cpp
    Effects/NuclearBomb.hpp
    Effects/NukeWave.cpp
    Effects/NukeWave.hpp
    Effects/ObjDemolish.cpp
    Effects/ObjDemolish.hpp
    Effects/ObjectExplosion.cpp
    Effects/ObjectExplosion.hpp
    Effects/ObjectExplosion.ipp
    Effects/Particles.cpp
    Effects/Particles.hpp
    Effects/PlasmaAura.cpp
    Effects/PlasmaAura.hpp
    Effects/PlasmaSplat.cpp
    Effects/PlasmaSplat.hpp
    Effects/Private/ExplosionPoint.hpp
    Effects/PuffData.hpp
    Effects/PulseAura.cpp
    Effects/PulseAura.hpp
    Effects/PulseSplat.cpp
    Effects/PulseSplat.hpp
    Effects/PunchBlast.cpp
    Effects/PunchBlast.hpp
    Effects/RaceChanger.cpp
    Effects/RaceChanger.hpp
    Effects/RaceChangerBody.cpp
    Effects/RadialDisc.cpp
    Effects/RadialDisc.hpp
    Effects/ResourceLoading.cpp
    Effects/ResourceLoading.hpp
    Effects/STFFlame.cpp
    Effects/STFFlame.hpp
    Effects/Scavenger.cpp
    Effects/Scavenger.hpp
    Effects/ShockWave.cpp
    Effects/ShockWave.hpp
    Effects/SmokeCloud.cpp
    Effects/SmokeCloud.hpp
    Effects/SmokePlume.cpp
    Effects/SmokePlume.hpp
    Effects/SmokePuff.cpp
    Effects/SmokePuff.hpp
    Effects/Sparks.cpp
    Effects/Sparks.hpp
    Effects/Torch.cpp
    Effects/Torch.hpp
    Effects/VapourPuff.cpp
    Effects/VapourPuff.hpp
    Effects/VapourTrail.cpp
    Effects/VapourTrail.hpp
    Effects/VortexBomb.cpp
    Effects/VortexBomb.hpp
    Effects/VortexSphere.cpp
    Effects/VortexSphere.hpp
    Effects/Waterfall.cpp
    Effects/Waterfall.hpp
    Effects/WhiteSphere.cpp
    Effects/WhiteSphere.hpp
    FirstPersonDriver.cpp
    FirstPersonDriver.hpp
    FirstPersonMachineDriver.cpp
    FirstPersonMachineDriver.hpp
    LandMine.cpp
    LandMine.hpp
    Locator.cpp
    Locator.hpp
    Locomotion/CanMove.hpp
    Locomotion/CanTurn.hpp
    Locomotion/EvasionPriorityPlan.cpp
    Locomotion/EvasionPriorityPlan.hpp
    Locomotion/EvasionPriorityPlans.cpp
    Locomotion/EvasionPriorityPlans.hpp
    Locomotion/Glider.cpp
    Locomotion/Glider.hpp
    Locomotion/GliderImpl.cpp
    Locomotion/HoverBoots.cpp
    Locomotion/HoverBoots.hpp
    Locomotion/HoverBootsImpl.cpp
    Locomotion/ITrack.cpp
    Locomotion/Internal/GliderImpl.hpp
    Locomotion/Internal/HoverBootsImpl.hpp
    Locomotion/Internal/ITrack.hpp
    Locomotion/Internal/LocomotionMethodImpl.hpp
    Locomotion/Internal/SpiderLegsImpl.hpp
    Locomotion/Internal/TracksImpl.hpp
    Locomotion/Internal/WheelsImpl.hpp
    Locomotion/LocomotionMethod.cpp
    Locomotion/LocomotionMethod.hpp
    Locomotion/LocomotionMethodImpl.cpp
    Locomotion/OrientationAndPositionPlan.cpp
    Locomotion/OrientationAndPositionPlan.hpp
    Locomotion/SpiderLegs.cpp
    Locomotion/SpiderLegs.hpp
    Locomotion/SpiderLegsImpl.cpp
    Locomotion/Tracks.cpp
    Locomotion/Tracks.hpp
    Locomotion/TracksImpl.cpp
    Locomotion/TurnerTracker.cpp
    Locomotion/TurnerTracker.hpp
    Locomotion/TurnerTracker.ipp
    Locomotion/Wheels.cpp
    Locomotion/Wheels.hpp
    Locomotion/WheelsImpl.cpp
    Machines/APC.cpp
    Machines/APC.hpp
    Machines/APCData.cpp
    Machines/APCData.hpp
    Machines/Administrator.cpp
    Machines/Administrator.hpp
    Machines/AdministratorData.cpp
    Machines/AdministratorData.hpp
    Machines/Aggressor.cpp
    Machines/Aggressor.hpp
    Machines/AggressorData.cpp
    Machines/AggressorData.hpp
    Machines/Constructor.cpp
    Machines/Constructor.hpp
    Machines/ConstructorData.cpp
    Machines/ConstructorData.hpp
    Machines/FacePlate.cpp
    Machines/FacePlate.hpp
    Machines/GeoLocator.cpp
    Machines/GeoLocator.hpp
    Machines/GeoLocatorData.cpp
    Machines/GeoLocatorData.hpp
    Machines/GeoLocatorImpl.cpp
    Machines/IMachineData.cpp
    Machines/IMachineExplosionData.cpp
    Machines/Internal/GeoLocatorImpl.hpp
    Machines/Internal/IMachineData.hpp
    Machines/Internal/IMachineData.ipp
    Machines/Internal/IMachineExplosionData.hpp
    Machines/Internal/IMachineExplosionData.ipp
    Machines/Internal/MachineImpl.hpp
    Machines/Internal/SpyLocatorImpl.hpp
    Machines/Machine.cpp
    Machines/Machine.hpp
    Machines/MachineDamageData.cpp
    Machines/MachineDamageData.hpp
    Machines/MachineData.cpp
    Machines/MachineData.hpp
    Machines/MachineExplosionData.cpp
    Machines/MachineExplosionData.hpp
    Machines/MachineImpl.cpp
    Machines/MachineMoveInfo.cpp
    Machines/MachineMoveInfo.hpp
    Machines/MachineMoveInfo.ipp
    Machines/MachineSpec.cpp
    Machines/MachineSpec.hpp
    Machines/ResourceCarrier.cpp
    Machines/ResourceCarrier.hpp
    Machines/ResourceCarrierData.cpp
    Machines/ResourceCarrierData.hpp
    Machines/SpyLocator.cpp
    Machines/SpyLocator.hpp
    Machines/SpyLocatorData.cpp
    Machines/SpyLocatorData.hpp
    Machines/SpyLocatorImpl.cpp
    Machines/Technician.cpp
    Machines/Technician.hpp
    Machines/TechnicianData.cpp
    Machines/TechnicianData.hpp
    Marker.cpp
    Marker.hpp
    MaterialConverter.cpp
    MaterialConverter.hpp
    ModelExporter.cpp
    ModelExporter.hpp
    MoveIndicator.cpp
    MoveIndicator.hpp
    ObjectFactory.ctf
    ObjectFactory.ctp
    ObjectFactory.hpp
    ObjectStoredFactory.ctp
    ObjectStoredFactory.hpp
    OreHolograph.cpp
    OreHolograph.hpp
    OreHolographData.cpp
    OreHolographData.hpp
    Persistence/ConstructionPersistence.cpp
    Persistence/ConstructionPersistence.hpp
    Persistence/DataStr.cpp
    Persistence/DataStr.hpp
    Persistence/MachinePersistence.cpp
    Persistence/MachinePersistence.hpp
    Persistence/OtherPersistence.cpp
    Persistence/OtherPersistence.hpp
    Persistence/Persistence.cpp
    Persistence/Persistence.hpp
    Persistence/WeaponPersistence.cpp
    Persistence/WeaponPersistence.hpp
    RampAcceleration.hpp
    Random.cpp
    Random.hpp
    SubId.ctp
    SubId.hpp
    Terrain/DomainAssignor.cpp
    Terrain/DomainAssignor.hpp
    Terrain/Internal/PlanetSurfaceImpl.hpp
    Terrain/PlanetSurface.cpp
    Terrain/PlanetSurface.hpp
    Terrain/PlanetSurface.ipp
    Terrain/PlanetSurfaceChecker.cpp
    Terrain/PlanetSurfaceChecker.hpp
    Terrain/PlanetSurfaceImpl.cpp
    Terrain/TerrainTile.cpp
    Terrain/TerrainTile.hpp
    Terrain/TileBoundary.cpp
    Terrain/TileBoundary.hpp
    Terrain/TileBoundary.ipp
    Terrain/TileData.cpp
    Terrain/TileData.hpp
    Terrain/TileData.ipp
    Weapons/Armourer.cpp
    Weapons/Armourer.hpp
    Weapons/BeeBomb.cpp
    Weapons/BeeBomb.hpp
    Weapons/BeeBomber.cpp
    Weapons/BeeBomber.hpp
    Weapons/Bolter.cpp
    Weapons/Bolter.hpp
    Weapons/CanAttack.cpp
    Weapons/CanAttack.hpp
    Weapons/CanAttackImpl.cpp
    Weapons/Electro.cpp
    Weapons/Electro.hpp
    Weapons/ElectroCharger.cpp
    Weapons/ElectroCharger.hpp
    Weapons/FlameThrower.cpp
    Weapons/FlameThrower.hpp
    Weapons/Internal/CanAttackImpl.hpp
    Weapons/Internal/LinearProjectileImpl.hpp
    Weapons/Internal/MissileImpl.hpp
    Weapons/IonWeapon.cpp
    Weapons/IonWeapon.hpp
    Weapons/LargeMissile.cpp
    Weapons/LargeMissile.hpp
    Weapons/LegalWeaponCombos.cpp
    Weapons/LegalWeaponCombos.hpp
    Weapons/LegalWeapons.cpp
    Weapons/LegalWeapons.hpp
    Weapons/LightSting.cpp
    Weapons/LightSting.hpp
    Weapons/LightStingWeapon.cpp
    Weapons/LightStingWeapon.hpp
    Weapons/LinearProjectile.cpp
    Weapons/LinearProjectile.hpp
    Weapons/LinearProjectileImpl.cpp
    Weapons/LinearWeapon.cpp
    Weapons/LinearWeapon.hpp
    Weapons/MetalSting.cpp
    Weapons/MetalSting.hpp
    Weapons/MetalStingWeapon.cpp
    Weapons/MetalStingWeapon.hpp
    Weapons/Missile.cpp
    Weapons/Missile.hpp
    Weapons/MissileImpl.cpp
    Weapons/MultiLauncher.cpp
    Weapons/MultiLauncher.hpp
    Weapons/NuclearWeapon.cpp
    Weapons/NuclearWeapon.hpp
    Weapons/PlasmaBolt.cpp
    Weapons/PlasmaBolt.hpp
    Weapons/PlasmaWeapon.cpp
    Weapons/PlasmaWeapon.hpp
    Weapons/PulseBlob.cpp
    Weapons/PulseBlob.hpp
    Weapons/PulseWeapon.cpp
    Weapons/PulseWeapon.hpp
    Weapons/PulseWeapon.ipp
    Weapons/PunchWeapon.cpp
    Weapons/PunchWeapon.hpp
    Weapons/SuperCharger.cpp
    Weapons/SuperCharger.hpp
    Weapons/TrailedProjectile.cpp
    Weapons/TrailedProjectile.hpp
    Weapons/TreacheryOrb.cpp
    Weapons/TreacheryOrb.hpp
    Weapons/TreacheryWeapon.cpp
    Weapons/TreacheryWeapon.hpp
    Weapons/VirusSpreader.cpp
    Weapons/VirusSpreader.hpp
    Weapons/VortexWeapon.cpp
    Weapons/VortexWeapon.hpp
    Weapons/Weapon.cpp
    Weapons/Weapon.hpp
    Weapons/Weapon.ipp
    Weapons/WeaponData.cpp
    Weapons/WeaponData.hpp
    Weapons/WeaponData.ipp
    Weapons/WeaponUtility.cpp
    Weapons/WeaponUtility.hpp
    machphys.cpp
    machphys.hpp
    ti_files/ti_admin.cpp
    ti_files/ti_aggr.cpp
    ti_files/ti_apc.cpp
    ti_files/ti_bk.cpp
    ti_files/ti_const.cpp
    ti_files/ti_fa.cpp
    ti_files/ti_ga.cpp
    ti_files/ti_gloc.cpp
    ti_files/ti_hw.cpp
    ti_files/ti_mis.cpp
    ti_files/ti_missi.cpp
    ti_files/ti_mn.cpp
    ti_files/ti_pod.cpp
    ti_files/ti_rcarr.cpp
    ti_files/ti_sloc.cpp
    ti_files/ti_sm.cpp
    ti_files/ti_tech.cpp
)

add_library(machphys STATIC ${MACHPHYS_SOURCES})
add_library(LibDev::machphys ALIAS machphys)

set_source_files_properties(
    Effects/Beam.cpp
    Effects/BeeBombWave.cpp
    Effects/CrackFire.cpp
    Effects/DebrisUnit.cpp
    Effects/LightStingSplat.cpp
    Effects/MachineExplosion.cpp
    Effects/MushroomShaft.cpp
    Effects/MushroomTop.cpp
    Effects/NuclearBomb.cpp
    Effects/NukeWave.cpp
    Effects/ObjectExplosion.cpp
    Effects/PlasmaSplat.cpp
    Effects/PulseSplat.cpp
    Effects/VortexBomb.cpp
    ti_files/ti_admin.cpp
    ti_files/ti_aggr.cpp
    ti_files/ti_apc.cpp
    ti_files/ti_bk.cpp
    ti_files/ti_const.cpp
    ti_files/ti_fa.cpp
    ti_files/ti_ga.cpp
    ti_files/ti_gloc.cpp
    ti_files/ti_hw.cpp
    ti_files/ti_mis.cpp
    ti_files/ti_missi.cpp
    ti_files/ti_mn.cpp
    ti_files/ti_pod.cpp
    ti_files/ti_rcarr.cpp
    ti_files/ti_sloc.cpp
    ti_files/ti_sm.cpp
    ti_files/ti_tech.cpp
    PROPERTIES
        SKIP_UNITY_BUILD_INCLUSION
            ON
)

target_link_libraries(machphys PUBLIC
    LibDev::ctl
    LibDev::environment
    LibDev::render
    LibDev::sim
)
