
set(PHYS_SOURCES
    ConfigSpace/ConfigSpace2d.cpp
    ConfigSpace/ConfigSpace2d.hpp
    ConfigSpace/ConfigSpace2d.ipp
    ConfigSpace/ConfigSpace2dImpl.cpp
    ConfigSpace/Domain.cpp
    ConfigSpace/DomainArc.cpp
    ConfigSpace/DomainFindPath.cpp
    ConfigSpace/DomainFindPathCache.cpp
    ConfigSpace/DomainGraph.cpp
    ConfigSpace/DomainVertex.cpp
    ConfigSpace/ExpansionSpace.cpp
    ConfigSpace/FindPath.cpp
    ConfigSpace/Internal/ConfigSpace2dImpl.hpp
    ConfigSpace/Internal/ConfigSpace2dImpl.ipp
    ConfigSpace/Internal/Domain.hpp
    ConfigSpace/Internal/Domain.ipp
    ConfigSpace/Internal/DomainArc.hpp
    ConfigSpace/Internal/DomainArc.ipp
    ConfigSpace/Internal/DomainFindPath.hpp
    ConfigSpace/Internal/DomainFindPath.ipp
    ConfigSpace/Internal/DomainFindPathCache.hpp
    ConfigSpace/Internal/DomainGraph.hpp
    ConfigSpace/Internal/DomainVertex.hpp
    ConfigSpace/Internal/DomainVertex.ipp
    ConfigSpace/Internal/ExpansionSpace.hpp
    ConfigSpace/Internal/ExpansionSpace.ipp
    ConfigSpace/Internal/FindPath.hpp
    ConfigSpace/Internal/FindPath.ipp
    ConfigSpace/Internal/MotionChunk.hpp
    ConfigSpace/Internal/MotionChunk.ipp
    ConfigSpace/Internal/Polygon.hpp
    ConfigSpace/Internal/Polygon.ipp
    ConfigSpace/Internal/Portal.hpp
    ConfigSpace/Internal/Portal.ipp
    ConfigSpace/Internal/VisibilityGraph.hpp
    ConfigSpace/Internal/VisibilityGraph.ipp
    ConfigSpace/MotionChunk.cpp
    ConfigSpace/PathFindingQueueWriter.cpp
    ConfigSpace/PathFindingQueueWriter.hpp
    ConfigSpace/Polygon.cpp
    ConfigSpace/Portal.cpp
    ConfigSpace/VisibilityGraph.cpp
    JonVec.hpp
    MotionControl/Brake.cpp
    MotionControl/Brake.hpp
    MotionControl/FlyControl.cpp
    MotionControl/FlyControl.hpp
    MotionControl/GroundFlyControl.cpp
    MotionControl/GroundFlyControl.hpp
    MotionControl/Motion.cpp
    MotionControl/Motion.hpp
    MotionControl/MotionControlWithTrans.cpp
    MotionControl/MotionControlWithTrans.hpp
    MotionControl/ThirdPerson.cpp
    MotionControl/ThirdPerson.hpp
    MotionControl/ZenithFlyControl.cpp
    MotionControl/ZenithFlyControl.hpp
    Persistence.cpp
    Persistence.hpp
    phys.cpp
    phys.hpp
    Plans/AcceleratedScalarPlan.cpp
    Plans/AcceleratedScalarPlan.hpp
    Plans/AcceleratedScalarPlanImpl.cpp
    Plans/AccelerateTumblePlan.cpp
    Plans/AccelerateTumblePlan.hpp
    Plans/AccelerateTumblePlanImpl.cpp
    Plans/AlignedBSPTree2d.hpp
    Plans/CompressedMotionChunk.cpp
    Plans/CompressedMotionChunk.hpp
    Plans/CompressedRampAcceleration.cpp
    Plans/CompressedRampAcceleration.hpp
    Plans/EulerTransform3d.cpp
    Plans/EulerTransform3d.hpp
    Plans/Internal/AcceleratedScalarPlanImpl.hpp
    Plans/Internal/AccelerateTumblePlanImpl.hpp
    Plans/Internal/LinearMotionPlanImpl.hpp
    Plans/Internal/LinearScalarPlanImpl.hpp
    Plans/Internal/LinearTravelPlanImpl.hpp
    Plans/Internal/MoveSpinPlanImpl.hpp
    Plans/Internal/TimedAnglePlanImpl.hpp
    Plans/Internal/TimedSpinPlanImpl.hpp
    Plans/LinearMotionPlan.cpp
    Plans/LinearMotionPlan.hpp
    Plans/LinearMotionPlanImpl.cpp
    Plans/LinearScalarPlan.cpp
    Plans/LinearScalarPlan.hpp
    Plans/LinearScalarPlanImpl.cpp
    Plans/LinearTravelPlan.cpp
    Plans/LinearTravelPlan.hpp
    Plans/LinearTravelPlanImpl.cpp
    Plans/MotionChunk.cpp
    Plans/MotionChunk.hpp
    Plans/MotionChunk.ipp
    Plans/MotionPlan.cpp
    Plans/MotionPlan.hpp
    Plans/MotionPlan.ipp
    Plans/MoveSpinPlan.cpp
    Plans/MoveSpinPlan.hpp
    Plans/MoveSpinPlanImpl.cpp
    Plans/RampAcceleration.cpp
    Plans/RampAcceleration.hpp
    Plans/RampAcceleration.ipp
    Plans/ScalarPlan.cpp
    Plans/ScalarPlan.hpp
    Plans/TimedAnglePlan.cpp
    Plans/TimedAnglePlan.hpp
    Plans/TimedAnglePlanImpl.cpp
    Plans/TimedSpinPlan.cpp
    Plans/TimedSpinPlan.hpp
    Plans/TimedSpinPlanImpl.cpp
    tiphys.cpp
    Trace.hpp
)

add_library(phys OBJECT ${PHYS_SOURCES})
add_library(LibDev::phys ALIAS phys)

target_link_libraries(phys PUBLIC
    LibDev::device
    LibDev::render
    LibDev::graph
)
